### ISSUE TITLE
No inverter in device list 

### ISSUE THREAD

**Issue by grydo** [DarkZeros/dbus-mppsolar#5]
Hello, in my Venus Os installed dbus-mppsolar without errors, in device list is not present inverter 

![Immagine2](https://github.com/user-attachments/assets/ed7ec068-0741-4e09-8a17-b1949231c272)

In system setup - Battery Measurement is present inverter

 
![Immagine](https://github.com/user-attachments/assets/fc3f56b2-d9e6-4d9d-9c04-92e2bbe66ecd)

what could be the problem?

**Comment by grydo** [comment]
This is the log


@4000000066b8abb219ac1ee4 *** CCGX booted (0) ***
@4000000066b8adbd1ee26cec *** CCGX booted (0) ***
@4000000066b8aedb1d4e72f4 *** CCGX booted (0) ***
@4000000066b8b2ef22b90bb4 *** CCGX booted (0) ***
@4000000066b8b4e21b43c25c *** starting dbus-mppsolar ***
@4000000066b8b4e52a9f4eec WARNING:root:Protocol PI30 is failing, switching to PI30MAX
@4000000066b8b4e538bb1fec WARNING:root:Connected to inverter on ttyUSB1 (PI30MAX), setting up dbus with /DeviceInstance = 0
@4000000066b8b4e600e149d4 Traceback (most recent call last):
@4000000066b8b4e600e170e4   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 177, in activate_name_owner
@4000000066b8b4e600e18854     return self.get_name_owner(bus_name)
@4000000066b8b4e600e197f4   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 361, in get_name_owner
@4000000066b8b4e600e1ab7c     return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
@4000000066b8b4e600e1bf04   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 666, in call_blocking
@4000000066b8b4e600e462cc     reply_message = self.send_message_with_reply_and_block(
@4000000066b8b4e600e47a3c dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'com.victronenergy.system': no such name
@4000000066b8b4e600e4997c 
@4000000066b8b4e600e4a14c During handling of the above exception, another exception occurred:
@4000000066b8b4e600e4b4d4 
@4000000066b8b4e600e55ccc Traceback (most recent call last):
@4000000066b8b4e600e56c6c   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 620, in <module>
@4000000066b8b4e600e583dc     main()
@4000000066b8b4e600e58bac   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 611, in main
@4000000066b8b4e600e59f34     mppservice = DbusMppSolarService(tty=args.serial.strip("/dev/"), deviceinstance=0)
@4000000066b8b4e600e5b6a4   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 129, in __init__
@4000000066b8b4e600e65e9c     self._systemDcPower = VeDbusItemImport(dbusconnection(), 'com.victronenergy.system', '/Dc/System/Power')
@4000000066b8b4e600e7a2d4   File "/data/etc/dbus-mppsolar/velib_python/vedbus.py", line 284, in __init__
@4000000066b8b4e600e7ba44     self._proxy = bus.get_object(serviceName, path, introspect=False)
@4000000066b8b4e600e7cdcc   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 241, in get_object
@4000000066b8b4e600e7e53c     return self.ProxyObjectClass(self, bus_name, object_path,
@4000000066b8b4e600e8b05c   File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 250, in __init__
@4000000066b8b4e600e8c7cc     self._named_service = conn.activate_name_owner(bus_name)
@4000000066b8b4e600e8db54   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 182, in activate_name_owner
@4000000066b8b4e600e8eedc     self.start_service_by_name(bus_name)
@4000000066b8b4e600e8fe7c   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 277, in start_service_by_name
@4000000066b8b4e600e9a28c     return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
@4000000066b8b4e600e9b9fc   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 666, in call_blocking
@4000000066b8b4e600e9d16c     reply_message = self.send_message_with_reply_and_block(
@4000000066b8b4e600e9e10c dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.victronenergy.system was not provided by any .service files
@4000000066b8b50230fd63b4 *** starting dbus-mppsolar ***
@4000000066b8b50600999274 WARNING:root:Protocol PI30 is failing, switching to PI30MAX
@4000000066b8b5060ece42a4 WARNING:root:Connected to inverter on ttyUSB1 (PI30MAX), setting up dbus with /DeviceInstance = 0
@4000000066b8b50611dbdc7c Traceback (most recent call last):
@4000000066b8b50611dc0774   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 177, in activate_name_owner
@4000000066b8b50611dc1afc     return self.get_name_owner(bus_name)
@4000000066b8b50611dc2a9c   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 361, in get_name_owner
@4000000066b8b50611dc3e24     return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
@4000000066b8b50611dc51ac   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 666, in call_blocking
@4000000066b8b50611e15ea4     reply_message = self.send_message_with_reply_and_block(
@4000000066b8b50611e17de4 dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'com.victronenergy.system': no such name
@4000000066b8b50611e1a10c 
@4000000066b8b50611e1a8dc During handling of the above exception, another exception occurred:
@4000000066b8b50611e1bc64 
@4000000066b8b50611e2ba4c Traceback (most recent call last):
@4000000066b8b50611e2c9ec   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 620, in <module>
@4000000066b8b50611e2dd74     main()
@4000000066b8b50611e2e544   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 611, in main
@4000000066b8b50611e2f8cc     mppservice = DbusMppSolarService(tty=args.serial.strip("/dev/"), deviceinstance=0)
@4000000066b8b50611e3103c   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 129, in __init__
@4000000066b8b50611e3c004     self._systemDcPower = VeDbusItemImport(dbusconnection(), 'com.victronenergy.system', '/Dc/System/Power')
@4000000066b8b50611e52764   File "/data/etc/dbus-mppsolar/velib_python/vedbus.py", line 284, in __init__
@4000000066b8b50611e542bc     self._proxy = bus.get_object(serviceName, path, introspect=False)
@4000000066b8b50611e55644   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 241, in get_object
@4000000066b8b50611e56db4     return self.ProxyObjectClass(self, bus_name, object_path,
@4000000066b8b50611e638d4   File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 250, in __init__
@4000000066b8b50611e6542c     self._named_service = conn.activate_name_owner(bus_name)
@4000000066b8b50611e667b4   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 182, in activate_name_owner
@4000000066b8b50611e67b3c     self.start_service_by_name(bus_name)
@4000000066b8b50611e68adc   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 277, in start_service_by_name
@4000000066b8b50611e76984     return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
@4000000066b8b50611e780f4   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 666, in call_blocking
@4000000066b8b50611e79c4c     reply_message = self.send_message_with_reply_and_block(
@4000000066b8b50611e7abec dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.victronenergy.system was not provided by any .service files
@4000000066b8b5183934c48c *** starting dbus-mppsolar ***
@4000000066b8b51c0cc2c304 WARNING:root:Protocol PI30 is failing, switching to PI30MAX
@4000000066b8b51c1ae959d4 WARNING:root:Connected to inverter on ttyUSB1 (PI30MAX), setting up dbus with /DeviceInstance = 0
@4000000066b8b51c1decd1ec Traceback (most recent call last):
@4000000066b8b51c1decfce4   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 177, in activate_name_owner
@4000000066b8b51c1ded1454     return self.get_name_owner(bus_name)
@4000000066b8b51c1ded23f4   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 361, in get_name_owner
@4000000066b8b51c1ded377c     return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
@4000000066b8b51c1ded4b04   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 666, in call_blocking
@4000000066b8b51c1deff2b4     reply_message = self.send_message_with_reply_and_block(
@4000000066b8b51c1df00a24 dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'com.victronenergy.system': no such name
@4000000066b8b51c1df02d4c 
@4000000066b8b51c1df03134 During handling of the above exception, another exception occurred:
@4000000066b8b51c1df048a4 
@4000000066b8b51c1df0fc54 Traceback (most recent call last):
@4000000066b8b51c1df10bf4   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 620, in <module>
@4000000066b8b51c1df12364     main()
@4000000066b8b51c1df12b34   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 611, in main
@4000000066b8b51c1df13ebc     mppservice = DbusMppSolarService(tty=args.serial.strip("/dev/"), deviceinstance=0)
@4000000066b8b51c1df15244   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 129, in __init__
@4000000066b8b51c1df4e454     self._systemDcPower = VeDbusItemImport(dbusconnection(), 'com.victronenergy.system', '/Dc/System/Power')
@4000000066b8b51c1df6bcfc   File "/data/etc/dbus-mppsolar/velib_python/vedbus.py", line 284, in __init__
@4000000066b8b51c1df6d854     self._proxy = bus.get_object(serviceName, path, introspect=False)
@4000000066b8b51c1df6ebdc   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 241, in get_object
@4000000066b8b51c1df6ff64     return self.ProxyObjectClass(self, bus_name, object_path,
@4000000066b8b51c1df7d63c   File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 250, in __init__
@4000000066b8b51c1df7f57c     self._named_service = conn.activate_name_owner(bus_name)
@4000000066b8b51c1df8051c   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 182, in activate_name_owner
@4000000066b8b51c1df81c8c     self.start_service_by_name(bus_name)
@4000000066b8b51c1df82c2c   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 277, in start_service_by_name
@4000000066b8b51c1df8eb94     return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
@4000000066b8b51c1df90304   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 666, in call_blocking
@4000000066b8b51c1df91a74     reply_message = self.send_message_with_reply_and_block(
@4000000066b8b51c1df92a14 dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.victronenergy.system was not provided by any .service files
@4000000066b8b52d017fd7ac *** starting dbus-mppsolar ***
@4000000066b8b5300cc19e0c WARNING:root:Protocol PI30 is failing, switching to PI30MAX
@4000000066b8b5301ad82b64 WARNING:root:Connected to inverter on ttyUSB1 (PI30MAX), setting up dbus with /DeviceInstance = 0
@4000000066b8b5301e1b8ec4 Traceback (most recent call last):
@4000000066b8b5301e1bb5d4   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 177, in activate_name_owner
@4000000066b8b5301e1bcd44     return self.get_name_owner(bus_name)
@4000000066b8b5301e1bd8fc   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 361, in get_name_owner
@4000000066b8b5301e1bf06c     return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
@4000000066b8b5301e1c000c   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 666, in call_blocking
@4000000066b8b5301e1ebf2c     reply_message = self.send_message_with_reply_and_block(
@4000000066b8b5301e1ed69c dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'com.victronenergy.system': no such name
@4000000066b8b5301e1ef9c4 
@4000000066b8b5301e1f0194 During handling of the above exception, another exception occurred:
@4000000066b8b5301e1f151c 
@4000000066b8b5301e1fccb4 Traceback (most recent call last):
@4000000066b8b5301e1fdc54   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 620, in <module>
@4000000066b8b5301e1fefdc     main()
@4000000066b8b5301e1ff7ac   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 611, in main
@4000000066b8b5301e200b34     mppservice = DbusMppSolarService(tty=args.serial.strip("/dev/"), deviceinstance=0)
@4000000066b8b5301e2022a4   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 129, in __init__
@4000000066b8b5301e20ce84     self._systemDcPower = VeDbusItemImport(dbusconnection(), 'com.victronenergy.system', '/Dc/System/Power')
@4000000066b8b5301e2212bc   File "/data/etc/dbus-mppsolar/velib_python/vedbus.py", line 284, in __init__
@4000000066b8b5301e222a2c     self._proxy = bus.get_object(serviceName, path, introspect=False)
@4000000066b8b5301e223db4   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 241, in get_object
@4000000066b8b5301e22513c     return self.ProxyObjectClass(self, bus_name, object_path,
@4000000066b8b5301e23148c   File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 250, in __init__
@4000000066b8b5301e232bfc     self._named_service = conn.activate_name_owner(bus_name)
@4000000066b8b5301e233f84   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 182, in activate_name_owner
@4000000066b8b5301e23530c     self.start_service_by_name(bus_name)
@4000000066b8b5301e2362ac   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 277, in start_service_by_name
@4000000066b8b5301e2648dc     return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
@4000000066b8b5301e266434   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 666, in call_blocking
@4000000066b8b5301e267ba4     reply_message = self.send_message_with_reply_and_block(
@4000000066b8b5301e268f2c dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.victronenergy.system was not provided by any .service files
@4000000066b8b54107b5c334 *** starting dbus-mppsolar ***
@4000000066b8b54414b742c4 WARNING:root:Protocol PI30 is failing, switching to PI30MAX
@4000000066b8b54422cb43c4 WARNING:root:Connected to inverter on ttyUSB1 (PI30MAX), setting up dbus with /DeviceInstance = 0
@4000000066b8b54425f3c06c Traceback (most recent call last):
@4000000066b8b54425f3f334   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 177, in activate_name_owner
@4000000066b8b54425f40aa4     return self.get_name_owner(bus_name)
@4000000066b8b54425f41a44   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 361, in get_name_owner
@4000000066b8b54425f42dcc     return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
@4000000066b8b54425f44154   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 666, in call_blocking
@4000000066b8b54425f70844     reply_message = self.send_message_with_reply_and_block(
@4000000066b8b54425f7239c dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'com.victronenergy.system': no such name
@4000000066b8b54425f742dc 
@4000000066b8b54425f74aac During handling of the above exception, another exception occurred:
@4000000066b8b54425f75e34 
@4000000066b8b54425f82954 Traceback (most recent call last):
@4000000066b8b54425f838f4   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 620, in <module>
@4000000066b8b54425f84c7c     main()
@4000000066b8b54425f8544c   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 611, in main
@4000000066b8b54425f867d4     mppservice = DbusMppSolarService(tty=args.serial.strip("/dev/"), deviceinstance=0)
@4000000066b8b54425f87f44   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 129, in __init__
@4000000066b8b54425f92354     self._systemDcPower = VeDbusItemImport(dbusconnection(), 'com.victronenergy.system', '/Dc/System/Power')
@4000000066b8b54425fa678c   File "/data/etc/dbus-mppsolar/velib_python/vedbus.py", line 284, in __init__
@4000000066b8b54425fa82e4     self._proxy = bus.get_object(serviceName, path, introspect=False)
@4000000066b8b54425fa966c   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 241, in get_object
@4000000066b8b54425faa9f4     return self.ProxyObjectClass(self, bus_name, object_path,
@4000000066b8b54425fb6574   File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 250, in __init__
@4000000066b8b54425fb7ce4     self._named_service = conn.activate_name_owner(bus_name)
@4000000066b8b54425fb8c84   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 182, in activate_name_owner
@4000000066b8b54425fba3f4     self.start_service_by_name(bus_name)
@4000000066b8b54425fbb394   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 277, in start_service_by_name
@4000000066b8b54425fc635c     return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
@4000000066b8b54425fc7acc   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 666, in call_blocking
@4000000066b8b54425fc923c     reply_message = self.send_message_with_reply_and_block(
@4000000066b8b54425fca5c4 dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.victronenergy.system was not provided by any .service files
@4000000066b8b555106f09f4 *** starting dbus-mppsolar ***
@4000000066b8b5581fbd38a4 WARNING:root:Protocol PI30 is failing, switching to PI30MAX
@4000000066b8b5582e232a34 WARNING:root:Connected to inverter on ttyUSB1 (PI30MAX), setting up dbus with /DeviceInstance = 0
@4000000066b8b55831d25f24 Traceback (most recent call last):
@4000000066b8b55831d28634   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 177, in activate_name_owner
@4000000066b8b55831d29da4     return self.get_name_owner(bus_name)
@4000000066b8b55831d2ad44   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 361, in get_name_owner
@4000000066b8b55831d2c0cc     return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
@4000000066b8b55831d2d454   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 666, in call_blocking
@4000000066b8b55831d54d24     reply_message = self.send_message_with_reply_and_block(
@4000000066b8b55831d560ac dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'com.victronenergy.system': no such name
@4000000066b8b55831d583d4 
@4000000066b8b55831d587bc During handling of the above exception, another exception occurred:
@4000000066b8b55831d59b44 
@4000000066b8b55831d64724 Traceback (most recent call last):
@4000000066b8b55831d656c4   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 620, in <module>
@4000000066b8b55831d66e34     main()
@4000000066b8b55831d6721c   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 611, in main
@4000000066b8b55831d685a4     mppservice = DbusMppSolarService(tty=args.serial.strip("/dev/"), deviceinstance=0)
@4000000066b8b55831d69d14   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 129, in __init__
@4000000066b8b55831d73954     self._systemDcPower = VeDbusItemImport(dbusconnection(), 'com.victronenergy.system', '/Dc/System/Power')
@4000000066b8b55831d86a04   File "/data/etc/dbus-mppsolar/velib_python/vedbus.py", line 284, in __init__
@4000000066b8b55831d88174     self._proxy = bus.get_object(serviceName, path, introspect=False)
@4000000066b8b55831d894fc   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 241, in get_object
@4000000066b8b55831d8a884     return self.ProxyObjectClass(self, bus_name, object_path,
@4000000066b8b55831d95c34   File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 250, in __init__
@4000000066b8b55831d973a4     self._named_service = conn.activate_name_owner(bus_name)
@4000000066b8b55831d9872c   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 182, in activate_name_owner
@4000000066b8b55831d99e9c     self.start_service_by_name(bus_name)
@4000000066b8b55831d9aa54   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 277, in start_service_by_name
@4000000066b8b55831da4694     return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
@4000000066b8b55831da5e04   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 666, in call_blocking
@4000000066b8b55831da7574     reply_message = self.send_message_with_reply_and_block(
@4000000066b8b55831da88fc dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.victronenergy.system was not provided by any .service files
@4000000066b8b56915f25304 *** starting dbus-mppsolar ***
@4000000066b8b56c398f8ad4 WARNING:root:Protocol PI30 is failing, switching to PI30MAX
@4000000066b8b56d0c34decc WARNING:root:Connected to inverter on ttyUSB1 (PI30MAX), setting up dbus with /DeviceInstance = 0
@4000000066b8b56d0f40a3e4 Traceback (most recent call last):
@4000000066b8b56d0f40d2c4   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 177, in activate_name_owner
@4000000066b8b56d0f40ea34     return self.get_name_owner(bus_name)
@4000000066b8b56d0f40f9d4   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 361, in get_name_owner
@4000000066b8b56d0f410d5c     return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
@4000000066b8b56d0f4120e4   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 666, in call_blocking
@4000000066b8b56d0f43b8f4     reply_message = self.send_message_with_reply_and_block(
@4000000066b8b56d0f43cc7c dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'com.victronenergy.system': no such name
@4000000066b8b56d0f43efa4 
@4000000066b8b56d0f43f774 During handling of the above exception, another exception occurred:
@4000000066b8b56d0f440714 
@4000000066b8b56d0f4660a4 Traceback (most recent call last):
@4000000066b8b56d0f467044   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 620, in <module>
@4000000066b8b56d0f4683cc     main()
@4000000066b8b56d0f468b9c   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 611, in main
@4000000066b8b56d0f469f24     mppservice = DbusMppSolarService(tty=args.serial.strip("/dev/"), deviceinstance=0)
@4000000066b8b56d0f46b694   File "/data/etc/dbus-mppsolar/dbus-mppsolar.py", line 129, in __init__
@4000000066b8b56d0f476274     self._systemDcPower = VeDbusItemImport(dbusconnection(), 'com.victronenergy.system', '/Dc/System/Power')
@4000000066b8b56d0f48a2c4   File "/data/etc/dbus-mppsolar/velib_python/vedbus.py", line 284, in __init__
@4000000066b8b56d0f48ba34     self._proxy = bus.get_object(serviceName, path, introspect=False)
@4000000066b8b56d0f48cdbc   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 241, in get_object
@4000000066b8b56d0f48e144     return self.ProxyObjectClass(self, bus_name, object_path,
@4000000066b8b56d0f498d24   File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 250, in __init__
@4000000066b8b56d0f49a494     self._named_service = conn.activate_name_owner(bus_name)
@4000000066b8b56d0f49b81c   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 182, in activate_name_owner
@4000000066b8b56d0f49cba4     self.start_service_by_name(bus_name)
@4000000066b8b56d0f49db44   File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 277, in start_service_by_name
@4000000066b8b56d0f4a833c     return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
@4000000066b8b56d0f4a9aac   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 666, in call_blocking
@4000000066b8b56d0f4ab21c     reply_message = self.send_message_with_reply_and_block(
@4000000066b8b56d0f4ac1bc dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.victronenergy.system was not provided by any .service files
@4000000066b8b58a20501e1c *** CCGX booted (0) ***

**Comment by DarkZeros** [comment]
This should already be fixed in the latest main. I added an exception for cases where the DCSystem is not present, not to perform the DC correction which is enabled by default

**Comment by grydo** [comment]
It doesn't work tried several times, tried restarting and changing cables.

**Comment by DarkZeros** [comment]
A newer log might help me fix the issue. I think I added exception handling but all possible external services, but I may have missed some
